# Generated by Django 4.2.1 on 2023-09-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_alter_interface_id_alter_realtor_id'),
        ('listings', '0003_rename_price_listing_area_rename_sqft_listing_floors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor'),
        ),
    ]
