# Generated by Django 4.2.1 on 2023-09-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_agent_profile_image"),
        ("listings", "0004_alter_listing_realtor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="realtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.agent",
            ),
        ),
    ]
