# Generated by Django 4.2.1 on 2024-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_alter_listing_realtor"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="english_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="french_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="german_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="greek_content",
            field=models.TextField(blank=True),
        ),
    ]
