# Generated by Django 4.2.1 on 2024-01-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_listing_english_content_listing_french_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
