# Generated by Django 4.2.1 on 2024-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_alter_listing_bathrooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="croatian_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="czech_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="dutch_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="norway_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="polish_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="russian_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="slovak_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="swedish_content",
            field=models.TextField(blank=True),
        ),
    ]
