# Generated by Django 4.2.1 on 2024-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_listing_croatian_content_listing_czech_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="domain",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="oib_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="portrait_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
    ]
