# Generated by Django 3.1.4 on 2022-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_topbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
