# Generated by Django 3.1.4 on 2022-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220313_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
