# Generated by Django 4.2.1 on 2024-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_article_id_alter_privacy_id_alter_topbar_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "home"),
                            ("about", "about"),
                            ("listings", "listings"),
                            ("listing details", "listing details"),
                            ("blog", "blog"),
                            ("blog details", "blog details"),
                            ("contact", "contact"),
                            ("privacy", "privacy"),
                            ("navbar", "navbar"),
                            ("footer", "footer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("english_content", models.TextField(blank=True)),
                ("german_content", models.TextField(blank=True)),
                ("french_content", models.TextField(blank=True)),
                ("greek_content", models.TextField(blank=True)),
                ("croatian_content", models.TextField(blank=True)),
                ("polish_content", models.TextField(blank=True)),
                ("czech_content", models.TextField(blank=True)),
                ("russian_content", models.TextField(blank=True)),
                ("swedish_content", models.TextField(blank=True)),
                ("norway_content", models.TextField(blank=True)),
                ("slovak_content", models.TextField(blank=True)),
                ("dutch_content", models.TextField(blank=True)),
            ],
        ),
    ]
