# Generated by Django 4.2.1 on 2024-02-15 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_alter_translation_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="translation",
            options={"ordering": ["name"]},
        ),
    ]
