# Generated by Django 4.2.1 on 2023-09-06 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agents",
            options={"ordering": ["-created"], "verbose_name_plural": "Agents"},
        ),
    ]
