# Generated by Django 4.2.1 on 2023-09-06 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_agents_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agents",
            options={
                "ordering": ["-created"],
                "verbose_name": "Agent",
                "verbose_name_plural": "Agent",
            },
        ),
    ]
