# Generated by Django 4.2.1 on 2023-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_agents_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='agents',
            name='counbtry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
