# Generated by Django 4.2.1 on 2023-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_location_agents_city_agents_counbtry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='agents',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
