# Generated by Django 4.2.1 on 2023-09-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_agent_username_otpverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='counbtry',
            new_name='country',
        ),
    ]
