# Generated by Django 4.2.1 on 2023-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_agent_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
    ]
