# Generated by Django 4.2.1 on 2023-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_agent_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company/"),
        ),
        migrations.AddField(
            model_name="agent",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="domain",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="oib_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="portrait_photo",
            field=models.ImageField(blank=True, null=True, upload_to="portrait/"),
        ),
    ]
