# Generated by Django 3.1.4 on 2022-03-05 02:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
