# Generated by Django 3.1.4 on 2022-03-05 03:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20220305_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
