# Generated by Django 4.2.1 on 2023-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realtors", "0004_interface_description2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interface",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="realtor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
